version: "3.9"
services:
  api:
    container_name: "body-fit-tracker-api"
    build: ./src/Api
    image: body-fit-tracker-api
    restart: "unless-stopped"
    env_file:
      - .env
    networks:
      - body-fit-tracker
    ports:
      - 5000:5000
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: "body-fit-tracker-db"
    image: postgres
    restart: "unless-stopped"
    env_file:
      - .env
    networks:
      - body-fit-tracker
    ports:
      - 5440:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - body-fit-tracker-db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "${POSTGRES_DB}"]

volumes:
  body-fit-tracker-db:

networks:
  body-fit-tracker:
