// <auto-generated />
using System;
using Api.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Api.Persistence.migrations
{
    [DbContext(typeof(BodyFitTrackerContext))]
    [Migration("20200606020714_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0");

            modelBuilder.Entity("Api.Domain.Models.AppUser", b =>
                {
                    b.Property<int>("AppUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HashedPassword")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Height")
                        .HasColumnType("REAL");

                    b.Property<string>("MeasurementSystemPreference")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Weight")
                        .HasColumnType("REAL");

                    b.HasKey("AppUserId");

                    b.ToTable("AppUsers");

                    b.HasData(
                        new
                        {
                            AppUserId = 1,
                            Email = "abc@gmail.com",
                            Gender = "Male",
                            HashedPassword = "abc",
                            Height = 60.0,
                            MeasurementSystemPreference = "Imperial",
                            Salt = "abc",
                            Weight = 120.0
                        });
                });

            modelBuilder.Entity("Api.Domain.Models.BodyMeasurement", b =>
                {
                    b.Property<int>("BodyMeasurementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AppUserId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("BodyFatPercentage")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("TEXT");

                    b.Property<double?>("HipCircumference")
                        .HasColumnType("REAL");

                    b.Property<double>("NeckCircumference")
                        .HasColumnType("REAL");

                    b.Property<double>("WaistCircumference")
                        .HasColumnType("REAL");

                    b.Property<double>("Weight")
                        .HasColumnType("REAL");

                    b.HasKey("BodyMeasurementId");

                    b.HasIndex("AppUserId");

                    b.ToTable("BodyMeasurements");

                    b.HasData(
                        new
                        {
                            BodyMeasurementId = 1,
                            AppUserId = 1,
                            BodyFatPercentage = 10.0,
                            DateAdded = new DateTime(2020, 6, 5, 0, 0, 0, 0, DateTimeKind.Local),
                            NeckCircumference = 12.0,
                            WaistCircumference = 28.0,
                            Weight = 125.0
                        },
                        new
                        {
                            BodyMeasurementId = 2,
                            AppUserId = 1,
                            BodyFatPercentage = 10.0,
                            DateAdded = new DateTime(2020, 6, 6, 0, 0, 0, 0, DateTimeKind.Local),
                            NeckCircumference = 12.0,
                            WaistCircumference = 28.0,
                            Weight = 125.0
                        },
                        new
                        {
                            BodyMeasurementId = 3,
                            AppUserId = 1,
                            BodyFatPercentage = 10.0,
                            DateAdded = new DateTime(2020, 6, 7, 0, 0, 0, 0, DateTimeKind.Local),
                            NeckCircumference = 12.0,
                            WaistCircumference = 28.0,
                            Weight = 125.0
                        },
                        new
                        {
                            BodyMeasurementId = 4,
                            AppUserId = 1,
                            BodyFatPercentage = 10.0,
                            DateAdded = new DateTime(2020, 6, 7, 0, 0, 0, 0, DateTimeKind.Local),
                            NeckCircumference = 12.0,
                            WaistCircumference = 28.0,
                            Weight = 125.0
                        },
                        new
                        {
                            BodyMeasurementId = 5,
                            AppUserId = 1,
                            BodyFatPercentage = 10.0,
                            DateAdded = new DateTime(2020, 6, 7, 0, 0, 0, 0, DateTimeKind.Local),
                            NeckCircumference = 12.0,
                            WaistCircumference = 28.0,
                            Weight = 125.0
                        },
                        new
                        {
                            BodyMeasurementId = 6,
                            AppUserId = 1,
                            BodyFatPercentage = 10.0,
                            DateAdded = new DateTime(2020, 6, 7, 0, 0, 0, 0, DateTimeKind.Local),
                            NeckCircumference = 12.0,
                            WaistCircumference = 28.0,
                            Weight = 125.0
                        },
                        new
                        {
                            BodyMeasurementId = 7,
                            AppUserId = 1,
                            BodyFatPercentage = 10.0,
                            DateAdded = new DateTime(2020, 6, 7, 0, 0, 0, 0, DateTimeKind.Local),
                            NeckCircumference = 12.0,
                            WaistCircumference = 28.0,
                            Weight = 125.0
                        },
                        new
                        {
                            BodyMeasurementId = 8,
                            AppUserId = 1,
                            BodyFatPercentage = 10.0,
                            DateAdded = new DateTime(2020, 6, 7, 0, 0, 0, 0, DateTimeKind.Local),
                            NeckCircumference = 12.0,
                            WaistCircumference = 28.0,
                            Weight = 125.0
                        },
                        new
                        {
                            BodyMeasurementId = 9,
                            AppUserId = 1,
                            BodyFatPercentage = 10.0,
                            DateAdded = new DateTime(2020, 6, 7, 0, 0, 0, 0, DateTimeKind.Local),
                            NeckCircumference = 12.0,
                            WaistCircumference = 28.0,
                            Weight = 125.0
                        },
                        new
                        {
                            BodyMeasurementId = 10,
                            AppUserId = 1,
                            BodyFatPercentage = 10.0,
                            DateAdded = new DateTime(2020, 6, 7, 0, 0, 0, 0, DateTimeKind.Local),
                            NeckCircumference = 12.0,
                            WaistCircumference = 28.0,
                            Weight = 125.0
                        });
                });

            modelBuilder.Entity("Api.Domain.Models.BodyMeasurement", b =>
                {
                    b.HasOne("Api.Domain.Models.AppUser", "AppUser")
                        .WithMany("BodyMeasurements")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
