name: Server Pipeline
on:
  push:
    paths:
      - "server/**"
      - ".github/workflows/serverPipeline.yml"
jobs:
  build-and-test-code:
    name: "Build & Test Code"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "7.0.x"
      - run: dotnet build
      - run: dotnet test

  build-docker-image:
    name: "Build Docker Image"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - working-directory: ./server
        run: docker build -t server-app .

  deploy-app:
    name: "Deploy App"
    needs: [build-and-test-code, build-docker-image]
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            cd programming/bodyFitTracker
            git pull
            cd server
            docker compose up --detach --build
